### ISSUE TITLE
Document the App Creation Requirements?

### ISSUE THREAD

**Issue by grumple-unithera** [ggpwnkthx/Microsoft-Graph-SMTP-Relay#1]
I have been looking for this, and glad I found this. However, I will try and figure it out but was curious if you could toss some documentation together on setting up the APP that's required.

**Comment by ggpwnkthx** [comment]
Generally speaking this should work just like a regular SMTP service. However, it accepts connections with no authentication as well as any LOGIN or PLAIN authentication without TLS or SSL. It is purposefully designed to be insecure in this way so that your other services can route the messages with little delay. 

So it's **VERY** important to make sure you air-gap the inbound networking for this service and never expose its SMTP port outside of your internal container network.

Are you using a Docker or Kubernetes environment? If you can provide the YAML file you're using (with sensitive data scrubbed) I can take a look at how this would fit in.

**Comment by ggpwnkthx** [comment]
Sorry, coffee hasn't kicked in yet. I just realized you meant how the registered app in AAD/Entra should be set up. Is that correct?

**Comment by grumple-unithera** [comment]
Yeah, I think I figured that part out, but having a different issue. Trying to figure it out now.

```
microsoft-graph-smtp-relay  | Traceback (most recent call last):
microsoft-graph-smtp-relay  |   File "/usr/local/lib/python3.12/site-packages/aiosmtpd/smtp.py", line 741, in _handle_client
microsoft-graph-smtp-relay  |     await method(arg)
microsoft-graph-smtp-relay  |   File "/usr/local/lib/python3.12/site-packages/aiosmtpd/smtp.py", line 1460, in smtp_DATA
microsoft-graph-smtp-relay  |     status = await self._call_handler_hook('DATA')
microsoft-graph-smtp-relay  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
microsoft-graph-smtp-relay  |   File "/usr/local/lib/python3.12/site-packages/aiosmtpd/smtp.py", line 473, in _call_handler_hook
microsoft-graph-smtp-relay  |     status = await hook(self, self.session, self.envelope, *args)
microsoft-graph-smtp-relay  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
microsoft-graph-smtp-relay  |   File "/usr/src/app/handlers/microsoft_graph.py", line 119, in handle_DATA
microsoft-graph-smtp-relay  |     + self.app.acquire_token_for_client(scopes=[".default"])["access_token"]
microsoft-graph-smtp-relay  |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
microsoft-graph-smtp-relay  | KeyError: 'access_token'

```
I'm running this in docker (using a docker compose, I modified it a bit)

```
version: "3"
services:
  smtp_relay:
    image: microsoft-graph-smtp-relay
    container_name: microsoft-graph-smtp-relay
    environment:
      AUTHORITY: "https://login.microsoftonline.com/xxxxxxxxxxxxx" # UPDATE THIS
      CLIENT_ID: "yyyyyyyyyyyyyyyyyyyyyy" # UPDATE THIS
      CLIENT_SECRET: "zzzzzzzzzzzzzzz" # UPDATE THIS
      SMTP_RELAY_HOSTNAME: "0.0.0.0"
      SMTP_RELAY_PORT: "25"
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "25:25"

```
